# Generated by Django 5.2 on 2025-04-20 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_orderitem_unit_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'permissions': [('cancel_promotion', 'can cancel promotion')]},
        ),
    ]
