# Generated by Django 5.2 on 2025-04-20 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__last_name', 'user__first_name'], 'permissions': [('view_history', 'can view history')]},
        ),
    ]
